### ISSUE TITLE
some questions and a statement of intent, if you don't mind

### ISSUE THREAD

**Issue by andyglick** [japkit/japkit#25]
Stefan, my name is Andy Glick. I live in the states outside of Philadelphia. I have submitted and have had accepted a small number of pull requests to a small number of projects. Sometimes I have made too many aggressive changes to a project's codebase without discussing them with the product owner, which in the case of japkit would be you.

My questions to start are, why Java 1.7 and not 1.8? Why haven't you updated the versions of both dependencies and Maven plugins to their current versions? Why don 't you use the Google Java error prone compiler? (http://errorprone.info/)

I am fairly intolerant of technical debt. If you take a look at my profile and list of repositories you will see that I have forked well over 300 projects, which even I agree is somewhat ridiculous. But FBOW I fork projects rather than cloning them because what I normally do 1st is apply possibly massive modifications to a project's pom files, and if I haven't forked the project what am I supposed to do with my changes?

So, having gotten the administrivial details out of the way let me say:

1) I am interested in helping with japkit
2) so far I have forked the main git repo
3) I intend to start bumping versions in the pom files, but don't intend to upgrade to jdk 1.8 for time enough to allow you to respond to this opening salvo  

I look forward to working with you,

Andy

**Comment by stefanocke** [comment]
Hello Andy,
thanks for your interest in japkit!

Regarding Java 1.7 vs Java 1.8:  I think the main reason is that there was no urgent reason to do so so far. 
I use japkit in Java 8 projects for code generation without any issues for some time now and it should also work with Java 9 projects (see also #24).
For developent of japkit itself, there was also no urgency to use Java 1.8, since it is based on xtend (http://www.eclipse.org/xtend/) which always supported lambdas / closures.

May I ask how you "found" japkit? Are you interested in using it for code generation or are you more interested in imroving quality of smaller github projects in general?

Best Regards,
Stefan.
