### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by shardt68** [japkit/japkit#65]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by de.japkit.el.javael3.patch.Jre9Compat (file:/.../com/github/japkit/japkit-javael3/1.25/japkit-javael3-1.25.jar) to method com.sun.tools.javac.code.Symbol.getEnclosingElement()
WARNING: Please consider reporting this to the maintainers of de.japkit.el.javael3.patch.Jre9Compat
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by stefanocke** [comment]
As long a you don't use Groovy but only Java EL , the illegal refelective access is fixed since a while now in japkit.
However, you will still see the warnings for reasons described here: https://bz.apache.org/bugzilla/show_bug.cgi?id=63781#c7


As soon as you use the option `--illegal-access=deny` for your JVM, the warnings will disappear.
This can be seen in japkit-examples build:
https://github.com/japkit/japkit-examples/runs/5526984518?check_suite_focus=true
